# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
name: spark-monitoring-jmx-exporter
services:
  spark:
    image: docker.io/bitnami/spark:3.5
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
      - SPARK_METRICS_ENABLED=true
    ports:
      - '8080:8080'
      - '12345:12345'
      - '4040:4040'
    volumes:
      - ./jmx-spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./jmx-metrics.properties:/opt/bitnami/spark/conf/metrics.properties
      - ./jmx_prometheus_javaagent-0.20.0.jar:/opt/bitnami/spark/jars/jmx_prometheus_javaagent-0.20.0.jar
      - ./jmx_config.yml:/opt/bitnami/spark/conf/jmx_config.yml
  # spark-worker:
  #   image: docker.io/bitnami/spark:3.5
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_USER=spark
  #   ports:
  #     - '8081:8081'
  #   volumes:
  #     - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  #     - ./metrics.properties:/opt/bitnami/spark/conf/metrics.properties
  # history-server:
  #   image: docker.io/bitnami/spark:3.5
  #   environment:
  #     - SPARK_MODE=worker 
  #     - SPARK_MASTER_URL=spark://spark:7077
  #     - SPARK_WORKER_MEMORY=1G
  #     - SPARK_WORKER_CORES=1
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_USER=spark
  #   ports:
  #     - '18080:18080'
  #     - '8082:8081'
  #   volumes:
  #     - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  #     - ./metrics.properties:/opt/bitnami/spark/conf/metrics.properties
  #     - ./spark-logs:/opt/spark/spark-events
  #   command:
  #     - ./sbin/start-history-server.sh
  # driver-server:
  #   image: docker.io/bitnami/spark:3.5
  #   command: 
  #     - ./bin/spark-shell
  #     - '--master'
  #     - 'spark://spark:7077'
  #     - '--deploy-mode'
  #     - 'client'
  #     - '--name'
  #     - 'first-app'
  #   ports:
  #     - '4040:4040'
  #   volumes:
  #     - ./driver.spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  #     - ./metrics.properties:/opt/bitnami/spark/conf/metrics.properties
  #   stdin_open: true # docker run -i
  #   tty: true # docker run -t

